/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as FichaRouteImport } from './routes/ficha'
import { Route as FichaIndexRouteImport } from './routes/ficha.index'
import { Route as FichaAbaRouteImport } from './routes/ficha.$aba'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaRoute = FichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaIndexRoute = FichaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FichaRoute,
} as any)
const FichaAbaRoute = FichaAbaRouteImport.update({
  id: '/$aba',
  path: '/$aba',
  getParentRoute: () => FichaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/ficha': typeof FichaRouteWithChildren
  '/ficha/$aba': typeof FichaAbaRoute
  '/ficha/': typeof FichaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/ficha/$aba': typeof FichaAbaRoute
  '/ficha': typeof FichaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/entrar': typeof EntrarRoute
  '/ficha': typeof FichaRouteWithChildren
  '/ficha/$aba': typeof FichaAbaRoute
  '/ficha/': typeof FichaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar' | '/entrar' | '/ficha' | '/ficha/$aba' | '/ficha/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar' | '/entrar' | '/ficha/$aba' | '/ficha'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/entrar'
    | '/ficha'
    | '/ficha/$aba'
    | '/ficha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  EntrarRoute: typeof EntrarRoute
  FichaRoute: typeof FichaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha': {
      id: '/ficha'
      path: '/ficha'
      fullPath: '/ficha'
      preLoaderRoute: typeof FichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha/': {
      id: '/ficha/'
      path: '/'
      fullPath: '/ficha/'
      preLoaderRoute: typeof FichaIndexRouteImport
      parentRoute: typeof FichaRoute
    }
    '/ficha/$aba': {
      id: '/ficha/$aba'
      path: '/$aba'
      fullPath: '/ficha/$aba'
      preLoaderRoute: typeof FichaAbaRouteImport
      parentRoute: typeof FichaRoute
    }
  }
}

interface FichaRouteChildren {
  FichaAbaRoute: typeof FichaAbaRoute
  FichaIndexRoute: typeof FichaIndexRoute
}

const FichaRouteChildren: FichaRouteChildren = {
  FichaAbaRoute: FichaAbaRoute,
  FichaIndexRoute: FichaIndexRoute,
}

const FichaRouteWithChildren = FichaRoute._addFileChildren(FichaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  EntrarRoute: EntrarRoute,
  FichaRoute: FichaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
